name: Full Stack Project Backend Pipeline

on:
    push:
        branches:
            - develop
            - uat
            - main

        paths:
            - 'apps/backend/**'
            - 'libs/shared/**'

jobs:
    backend:
        name: Backend Build and Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to DockerHub
              uses: docker/login-action@v3.3.0
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            # - name: Set environment for backend
            #   id: set-env
            #   run: |
            #       if [[ $GITHUB_REF == refs/heads/develop ]]; then
            #         echo "env=develop" >> $GITHUB_ENV
            #         echo "docker_tag=develop" >> $GITHUB_ENV
            #         echo "render_service_id=${{ secrets.RENDER_BACKEND_SERVICE_DEV }}" >> $GITHUB_ENV
            #       elif [[ $GITHUB_REF == refs/heads/uat ]]; then
            #         echo "env=uat" >> $GITHUB_ENV
            #         echo "docker_tag=uat" >> $GITHUB_ENV
            #         echo "render_service_id=${{ secrets.RENDER_BACKEND_SERVICE_UAT }}" >> $GITHUB_ENV
            #       elif [[ $GITHUB_REF == refs/heads/main ]]; then
            #         echo "env=prod" >> $GITHUB_ENV
            #         echo "docker_tag=prod" >> $GITHUB_ENV
            #         echo "render_service_id=${{ secrets.RENDER_BACKEND_SERVICE_PROD }}" >> $GITHUB_ENV
            #       fi

            # - name: Build Backend Docker Image
            #   run: |
            #       docker build \
            #         --build-arg APP_ENV=${{ secrets.APP_ENV }} \
            #         --build-arg PORT_BACKEND=${{ secrets.PORT_BACKEND }} \
            #         --build-arg PORT_FRONTEND=${{ secrets.PORT_FRONTEND }} \
            #         --build-arg ROUTE_PREFIX=${{ secrets.ROUTE_PREFIX }} \
            #         --build-arg KEY_VAULT_URI=${{ secrets.KEY_VAULT_URI }} \
            #         --build-arg TENANT_ID=${{ secrets.TENANT_ID }} \
            #         --build-arg CLIENT_ID=${{ secrets.CLIENT_ID }} \
            #         --build-arg CLIENT_SECRET=${{ secrets.CLIENT_SECRET }} \
            #         -t ${{ secrets.DOCKER_USERNAME }}/backend:${{ env.docker_tag }} \
            #         -f devops/backend/Dockerfile .

            # - name: Push Backend Image to DockerHub
            #   run: |
            #       docker push ${{ secrets.DOCKER_USERNAME }}/backend:${{ env.docker_tag }}

            # - name: Deploy Backend to Render
            #   run: |
            #       curl -X POST -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            #       -H "Content-Type: application/json" \
            #       --data '{
            #         "serviceId": "${{ env.render_service_id }}",
            #         "image": "${{ secrets.DOCKER_USERNAME }}/backend:${{ env.docker_tag }}",
            #         "clearCache": true
            #       }' \
            #       ${{ secrets.RENDER_API_URL }}/v1/services/${{ env.render_service_id }}/deploys
