name: Full Stack Project Pipeline

on:
    push:
        branches:
            - develop
            - uat
            - main
        paths:
            - 'apps/frontend/**'
            - 'apps/backend/**'
            - 'libs/shared/**'

jobs:
    backend:
        name: Backend Build and Deploy
        runs-on: ubuntu-latest
        if: |
            contains(github.event.head_commit.modified, 'apps/backend/') ||
            contains(github.event.head_commit.modified, 'libs/shared/')

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to DockerHub
              uses: docker/login-action@v2.1.0
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            # Add remaining steps to build and deploy backend here

    frontend:
        name: Frontend Build and Deploy
        runs-on: ubuntu-latest
        if: |
            contains(github.event.head_commit.modified, 'apps/frontend/') ||
            contains(github.event.head_commit.modified, 'libs/shared/')

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to DockerHub
              uses: docker/login-action@v2.1.0
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            # Add remaining steps to build and deploy frontend here
