name: frontend_pipeline
run-name: frontend deployment by ${{ github.actor }}

on:
    push:
        branches:
            - develop
            - uat
            - main
        paths:
            - 'apps/frontend/**'
            - 'libs/shared/**'

jobs:
    frontend:
        name: Frontend Build and Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to DockerHub
              uses: docker/login-action@v3.3.0
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Set Environment Variables
              id: set-env
              run: |
                  case $GITHUB_REF in
                    refs/heads/develop)
                      echo "env=develop" >> $GITHUB_ENV
                      echo "APP_ENV=DEV" >> $GITHUB_ENV
                      echo "docker_tag=develop" >> $GITHUB_ENV
                      echo "render_service_id=${{ secrets.RENDER_FRONTEND_SERVICE_DEV }}" >> $GITHUB_ENV
                      ;;
                    refs/heads/uat)
                      echo "env=uat" >> $GITHUB_ENV
                      echo "APP_ENV=UAT" >> $GITHUB_ENV
                      echo "docker_tag=uat" >> $GITHUB_ENV
                      echo "render_service_id=${{ secrets.RENDER_FRONTEND_SERVICE_UAT }}" >> $GITHUB_ENV
                      ;;
                    refs/heads/main)
                      echo "env=prod" >> $GITHUB_ENV
                      echo "APP_ENV=PROD" >> $GITHUB_ENV
                      echo "docker_tag=prod" >> $GITHUB_ENV
                      echo "render_service_id=${{ secrets.RENDER_FRONTEND_SERVICE_PROD }}" >> $GITHUB_ENV
                      ;;
                  esac

            - name: Build and Push Frontend Docker Image
              uses: docker/build-push-action@v6
              with:
                  context: .
                  file: devops/frontend/Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKER_USERNAME }}/frontend:${{ env.docker_tag }}
                  build-args: |
                      APP_ENV=${{ env.APP_ENV }}
                      PORT_FRONTEND=${{ secrets.PORT_FRONTEND }}
