name: frontend_pipeline
run-name: frontend deployment by ${{ github.actor }}

on:
    push:
        branches:
            - develop
            - uat
            - main
        paths:
            - 'apps/frontend/**'
            - 'libs/shared/**'

jobs:
    frontend:
        name: Frontend Build and Deploy
        runs-on: ubuntu-latest
        timeout-minutes: 5
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to DockerHub
              uses: docker/login-action@v3.3.0
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Set Environment Variables
              id: set-env
              run: |
                  case $GITHUB_REF in
                    refs/heads/develop)
                      echo "env=develop" >> $GITHUB_ENV
                      echo "APP_ENV=DEV" >> $GITHUB_ENV
                      echo "PORT_FRONTEND=80" >> $GITHUB_ENV
                      echo "docker_tag=develop" >> $GITHUB_ENV
                      echo "railway_token=${{ secrets.DEV_RAILWAY_TOKEN }}" >> $GITHUB_ENV
                      ;;
                    refs/heads/uat)
                      echo "env=uat" >> $GITHUB_ENV
                      echo "APP_ENV=UAT" >> $GITHUB_ENV
                      echo "PORT_FRONTEND=80" >> $GITHUB_ENV
                      echo "docker_tag=uat" >> $GITHUB_ENV
                      echo "railway_token=${{ secrets.UAT_RAILWAY_TOKEN }}" >> $GITHUB_ENV
                      ;;
                    refs/heads/main)
                      echo "env=prod" >> $GITHUB_ENV
                      echo "APP_ENV=PROD" >> $GITHUB_ENV
                      echo "PORT_FRONTEND=80" >> $GITHUB_ENV
                      echo "docker_tag=prod" >> $GITHUB_ENV
                      echo "railway_token=${{ secrets.PROD_RAILWAY_TOKEN }}" >> $GITHUB_ENV
                      ;;
                  esac

            - name: Build and Push Frontend Docker Image
              uses: docker/build-push-action@v6
              with:
                  context: .
                  file: devops/frontend/Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKER_USERNAME }}/frontend:${{ env.docker_tag }}
                  build-args: |
                      APP_ENV=${{ env.APP_ENV }}
                      PORT_FRONTEND=${{ env.PORT_FRONTEND }}
              env:
                  APP_ENV: ${{ env.APP_ENV }}
                  PORT_FRONTEND: ${{ env.PORT_FRONTEND }}

            - name: Install Railway
              run: npm i -g @railway/cli

            - name: Deploy
              run: railway up --image ${{ secrets.DOCKER_USERNAME }}/frontend:${{ env.docker_tag }}
              env:
                  RAILWAY_TOKEN: ${{ env.railway_token }}
